### PR TITLE
Knowledge DB and D3.5 diagrams

### PR DESCRIPTION
**Pull request by nmsa**
* Adjustments made to the relational data model to accommodate the metamodel.
  * MetricComponent -> LeafAttribute
  * MetricComposition -> CompositeAttribute
  * add attribute "attributeAggregationOperator" in the "CompositeAttribute" entity
  * `LeafAttribute`: Rename attributeAggregationOperator -> metricAggregationOperator
  * `LeafAttribute`: Add the attributes normalizationKind and normalizationMetric
  * `Metric`: Remove normalizationKind attribute
  * `QualityModel`: Add "businessThreshold" attribute
  * Rename "threshold" attribute from "Metric" to "normalizationThreshold"

* Maven archetype moved from tma-framework-m.
   * Minor update for version 1.1
   * Documentation and usage updated.

* TMA Framework Modules updated.

### CODE REVIEW

**Comment by brenofranca83** [comment]
@jreluiz see this!

**Comment by nmsa** [comment]
@brenofranca83, @jreluiz, @joseadp is doing minor adjustments. 
I suggest that we discuss next week before closing this, to make sure everything can be accommodated.

**Comment by brenofranca83** [comment]
> @brenofranca83, @jreluiz, @joseadp is doing minor adjustments.
> I suggest that we discuss next week before closing this, to make sure everything can be accommodated.

@nmsa , next week I'll be probably offline at a conference in Havana/Cuba. But we can discuss it via e-mail. Another option is to discuss with @jreluiz and I can synch later.

**Comment by jreluiz** [comment]
@nmsa, by me it can be by email too. Since I work all day it is a bit complicated to find a free time for a video call.

**Pull request merged**
